DjangoTaskW3E/DjangoTaskW3E/urls.py
from django import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EcommerceApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoTaskW3E/EcommerceApp/urls.py
from django.urls import path
from django.conf import settings
from .views import views
from django.conf.urls.static import static

app_name = 'EcommerceApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/', views.products, name='products'),
    path('product/<name>', views.product, name='product'),
    path('addReview/<name>', views.addReview, name='addReview'),
    # path('category/<int:id>', views.category, name='category'),
    # path('cart/', views.cart, name='cart'),
    # path('checkout/', views.checkout, name='checkout'),
    # path('update_item/', views.updateItem, name='update_item'),
    # path('process_order/', views.processOrder, name='process_order'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoTaskW3E/EcommerceApp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator

# Create your models here.
class Product(models.Model):
    id
    name = models.CharField(max_length=200, validators=[MinLengthValidator(2)], unique=True, null=False, blank=False)
    price = models.FloatField(validators=[MinValueValidator(0.0) ,MaxValueValidator(9999.0)], null=False, blank=False, default=0)
    description = models.TextField(validators=[MinLengthValidator(10)], null=True)
    publisher = models.CharField(max_length=200, validators=[MinLengthValidator(2)], null=False, blank=False)
    developer = models.CharField(max_length=200, validators=[MinLengthValidator(2)], null=False, blank=False)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    titleimage = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.name
    

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.CharField(max_length=200, validators=[MinLengthValidator(2)], null=False, blank=False,  default="Anonymous")
    text = models.TextField(max_length=10000, validators=[MinLengthValidator(3)], null=False, blank=False)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(0.0) ,MaxValueValidator(5.0)])
    
    def __str__(self):
        return f"Review for {self.product.name} by {self.user}"

DjangoTaskW3E/EcommerceApp/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render

from .models import Product

# Create your views here.

class views:

    def home(request):
        return redirect("/product")
    
    def product(request, name):
        
        try:
            product = Product.objects.get(name=name)
            reviews = [{
                    'user': review.user,
                    'text': review.text,
                    'rating': review.rating
                } for review in product.reviews.all()]
            
            # print(reviews, product)
            return render(request, 'product.html', { 'product': product, 'reviews': reviews })
        except Product.DoesNotExist:
            raise Http404("Product does not exist")
    
    def products(request):            
        search_query = request.GET.get('search', '')
        products = []
        msg = None

        if search_query and len(search_query) > 2:
            products = Product.objects.filter(name__icontains=search_query)
        elif search_query and len(search_query) <= 2:
            msg = "Query length should be at least 3 characters"
            products = Product.objects.all()
        else:
            products = Product.objects.all()
        return render(request, 'products.html', {'products': products, 'msg': msg})
    
    def addReview(request, name):
        if request.method == 'POST':
            product = Product.objects.get(name=name)
            if not product:
                raise Http404("Product does not exist")
            elif request.POST['user'] == '' or request.POST['review'] == '' or request.POST['rating'] == '':
                return HttpResponse("Please fill all the fields")
            product.reviews.create(user=request.POST['user'], text=request.POST['review'], rating=request.POST['rating'])
            return render(request, 'product.html', { 'product': product, 'msg': 'Review added successfully' })

DjangoTaskW3E/EcommerceApp/templates/errorbanner.html
{% if msg %}
<div id="messageBlock" class="inset-x-0 bottom-0 py-2 sm:pb-5 w-full">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="rounded-lg bg-red-600 p-2 shadow-lg sm:p-3">
        <div class="flex flex-wrap items-center justify-between">
            <div class="flex w-0 flex-1 items-center">
                <span class="flex rounded-lg bg-red-800 p-2">
                <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M10.34 15.84c-.688-.06-1.386-.09-2.09-.09H7.5a4.5 4.5 0 110-9h.75c.704 0 1.402-.03 2.09-.09m0 9.18c.253.962.584 1.892.985 2.783.247.55.06 1.21-.463 1.511l-.657.38c-.551.318-1.26.117-1.527-.461a20.845 20.845 0 01-1.44-4.282m3.102.069a18.03 18.03 0 01-.59-4.59c0-1.586.205-3.124.59-4.59m0 9.18a23.848 23.848 0 018.835 2.535M10.34 6.66a23.847 23.847 0 008.835-2.535m0 0A23.74 23.74 0 0018.795 3m.38 1.125a23.91 23.91 0 011.014 5.395m-1.014 8.855c-.118.38-.245.754-.38 1.125m.38-1.125a23.91 23.91 0 001.014-5.395m0-3.46c.495.413.811 1.035.811 1.73 0 .695-.316 1.317-.811 1.73m0-3.46a24.347 24.347 0 010 3.46" />
                </svg>
                </span>
                <p class="ml-3 truncate font-medium text-white">
                <span class="inline">{{ msg }}</span>
                </p>
            </div>
            <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-2">
                <button id="dismissButton" type="button" class="-mr-1 flex rounded-md p-2 hover:bg-red-500 focus:outline-none focus:ring-2 focus:ring-white"
                    onclick="document.getElementById('messageBlock').style.display = 'none';"
                >
                <span class="sr-only">Dismiss</span>
                <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
                </button>
            </div>
        </div>
      </div>
    </div>
</div>

{% endif %}

DjangoTaskW3E/EcommerceApp/templates/index.html
<!-- djangotemplates/example/templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Django Sample Site - {% block title %}{% endblock %}
    </title>

    <script src="{% static 'js/main.js' %}"></script> <!-- This is how to include a static file -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
  </head>
  <body>
    <div class="container">
      {% block pagecontent %}
      {% endblock %}
    </div>
  </body>
</html>

DjangoTaskW3E/EcommerceApp/templates/navbar.html
<header class="bg-gray-800 w-full">
    <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:divide-y lg:divide-gray-700 lg:px-8">
      <form class="relative flex h-16 justify-between" method='GET' action="">
        <div class="relative z-10 flex px-2 lg:px-0">
          <a href="/product" class="flex flex-shrink-0 items-center">
            <img class="block h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </a>
        </div>
        <div class="relative z-0 flex flex-1 items-center justify-center px-2 sm:absolute sm:inset-0">
          <div class="w-full sm:max-w-xs">
            <label for="search" class="sr-only">Search</label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
                </svg>
              </div>
              <input id="search" name="search" class="block w-full rounded-md border border-transparent bg-gray-700 py-2 pl-10 pr-3 text-sm placeholder-gray-400 focus:border-white focus:bg-white focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-white sm:text-sm" placeholder="Search" type="search">
            </div>
          </div>
        </div>
        <div class="lg:relative lg:z-10 lg:ml-4 flex items-center">
          <div class="relative ml-4 flex-shrink-0">
            <div>
              <button type="submit" class="flex rounded-full bg-gray-800 text-sm text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </button>
            </div>
          </div>
        </div>
    </form>
    </div>
</header>

DjangoTaskW3E/EcommerceApp/templates/product.html
<script src="https://cdn.tailwindcss.com"></script>


{% include './navbar.html' %}
{% include './errorbanner.html' %}

<main class="mx-auto mt-8 max-w-2xl px-4 pb-16 sm:px-6 sm:pb-24 lg:max-w-7xl lg:px-8">
    <div class="lg:grid lg:auto-rows-min lg:grid-cols-12 lg:gap-x-8">
        <div class="mt-8 lg:col-span-7 lg:col-start-1 lg:row-span-3 lg:row-start-1 lg:mt-0">
            <img src="{{ product.image.url }}" alt="Back of women's Basic Tee in black." class="lg:col-span-2 lg:row-span-2 rounded-lg">
        </div>
        <div class="lg:col-span-5 lg:col-start-8 px-4 py-10">
            <div class="flex flex-col gap-5 justify-between">
                <h1 class="text-4xl font-medium text-gray-900 lg:mb-10">{{ product.name }}</h1>
                <p class="text-xl font-medium text-gray-900">Price: {{ product.price }}$</p>
                <p class="text-xl font-medium text-gray-900">Developer: {{ product.developer }}</p>
                <p class="text-xl font-medium text-gray-900">Publisher: {{ product.publisher }}</p>
            </div>
        </div>
    </div>
    
    <section aria-labelledby="reviews-heading" class="mt-16 sm:mt-24">
        <h2 id="reviews-heading" class="text-lg font-medium text-gray-900">Description</h2>
        <p class="mt-3 text-md text-gray-500">
            {{ product.description }}
        </p>
    </section>
    

    <!-- Reviews -->
    <section aria-labelledby="reviews-heading" class="mt-16 sm:mt-24">    
        <form action="{% url 'EcommerceApp:addReview' product.name %}" method="post" class="relative">
            <div class="overflow-hidden rounded-lg border border-gray-300 shadow-sm focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500">
                {% csrf_token %}
                <label for="title" class="sr-only">Username</label>
                <input type="text" name="user" id="username" class="block w-full border-0 p-5 pb-0 text-lg font-medium placeholder-gray-500 focus:ring-0" placeholder="Username">
                <label for="rating" class="sr-only">Rating</label>
                <input type="number" name="rating" id="rating" class="block w-full border-0 p-5 pb-0 text-lg font-medium placeholder-gray-500 focus:ring-0" placeholder="Rating">
                <label for="description" class="sr-only">Description</label>
                <div class='py-5'> 
                    <textarea rows="5" name="review" id="description" class="block w-full px-5 resize-none border-0 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="Write a review..."></textarea>
                </div>

              <!-- Spacer element to match the height of the toolbar -->
              <div aria-hidden="true">
                <div class="py-2">
                  <div class="h-9"></div>
                </div>
                <div class="h-px"></div>
              </div>
            </div>
          
            <div class="absolute inset-x-px bottom-0">
              <div class="flex items-center justify-right space-x-3 border-t border-gray-200 px-2 py-2 sm:px-3">
                <div class="flex-shrink-0">
                  <button type="submit" class="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Create</button>
                </div>
              </div>
            </div>
        </form>
        <h2 id="reviews-heading" class="text-lg font-medium text-gray-900 pt-12">Recent reviews</h2>
        {% for review in reviews %}
        <div class="mt-6 space-y-10 divide-y divide-gray-200 border-t border-b border-gray-200 pb-10">
            <div class="pt-10 flex flex-col lg:flex-row gap-2 lg:gap-5 px-8">
                <p class="mt-3 space-y-6 font-medium text-gray-900">{{ review.user }}</p>
                <p class="mt-3 space-y-6 text-sm text-gray-500">{{ review.text }}</p>
            </div>
        </div>
        {% endfor %}
    </section>

  </main>

DjangoTaskW3E/EcommerceApp/templates/products.html
<!-- djangotemplates/example/templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Django Sample Site - {% block title %}{% endblock %}
    </title>

    <script src="{% static 'script.js' %}"></script> <!-- This is how to include a static file -->
    <script src="https://cdn.tailwindcss.com"></script>
    {% comment %} <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" /> {% endcomment %}
  </head>
  <body class="grid place-items-center">
    {% include './navbar.html' %}
    {% include './errorbanner.html' %}
    <div class="container">
        {% comment %} {% block pagecontent %}
        {% endblock %} {% endcomment %}

        {% block content %}
        <div class="bg-white">
        <div class="mx-auto max-w-2xl pt-10 pb-16 px-4 sm:pb-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 id="products-heading" class="sr-only">
            Products
            </h2>

            <div class="grid grid-cols-1 gap-y-10 gap-x-6 md:grid-cols-2 lg:grid-cols-4 xl:gap-x-8 mx-12 sm:mx-0">
            {% for product in products %}
            <a href="{{ product.name }}" class="group">
                <div class="aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-lg">
                    <img src="{{ product.titleimage.url }}" class="w-full object-cover object-center group-hover:opacity-75 h-96" />
                </div>
                <div class="mt-4 flex items-center justify-between text-base font-medium text-gray-900">
                <h3>{{ product.name }}</h3>
                <p>{{ product.price }}$</p>
                </div>
                {% comment %} <p class="mt-1 text-sm italic text-gray-500">{{ product.description }}</p> {% endcomment %}
            </a>
            {% endfor %}
            </div>
        </div>
        </div>
        {% endblock %}
    </div>
  </body>
</html>